### ISSUE TITLE
一些论文理解问题

### ISSUE THREAD

**Issue by NoviceCrom** [genggengcss/PDKGC#7]
1. 方法C部分公式4中的Wr的维度是Rd吗？B部分末尾的r的维度是Rd吗？

2.关于方法D部分中：
![image](https://github.com/genggengcss/PDKGC/assets/48437212/d7945645-b7bb-403c-8a4b-f3c570cc3baa)
根据公式每个component embedding应该对应更新一个关系embedding，在提示p中似乎只体现了K个component embedding和一个Pr，应该如何理解这个Pr呢？

**Comment by genggengcss** [comment]
1. 是的，W_r, r, v^k, 的维度都是一致的，即d=200;
2. 提示p中包含的是，当前实体的K个component embedding和当前关系的embedding，对应转化成的token sequence，所以这个提示是一个长度为(K+1)*n的sequence

**Comment by NoviceCrom** [comment]
![Uploading image.png…]()
1.所以这个公式更新的hr指的都是与那些邻居节点相连的那些关系吗？2.右边乘这个 transformation matrix矩阵维度是R(d*d)吗？3.那么最后转化为提示p中的关系embedding也是与邻居节点相连的那些关系吗？

**Comment by anonimous123456** [comment]
是的，就是图谱里面的那些关系。

**Comment by zeng-orc** [comment]
是的，也就是知识图谱中的那些关系
